version: '2'
services:
  web:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./shinyapps/:/srv/shiny-server/
      #- ./data/:/srv/data/
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/
    command: ["/usr/bin/shiny-server.sh"]
  nginx:
    restart: always
    build: ./nginx
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
