version: '2'
services:
  web:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./shinyapps:/srv/shiny-server/
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/
    command: ["/usr/bin/shiny-server.sh"]

