version: '3'
services:
    nginx:
        build: ./nginx
        links:
            - node1:node1
            - node2:node2
            - node3:node3
        ports:
            - "80:80"
    node1:
        build: ./node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./node/:/src
        environment:
            - NODE_SERVER=production1
        cpu_limit : 1 
    node2:
        build: ./node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./node/:/src
        environment:
            - NODE_SERVER=production2
    node3:
        build: ./node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./node/:/src
        environment:
            - NODE_SERVER=production3
    redis:
        image: redis
        ports:
            - "6379"