version: '2'
services:
  webapp:
    build: .
    # ports:
    #   - "80:3838"
    expose:
      - "3838"
    volumes:
      - ./shinyapps/:/srv/shiny-server/
      #- ./data/:/srv/data/
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/
    command: ["/usr/bin/shiny-server.sh"]
  # webapp:
  #   build: ./testweb
  #   # ports:
  #   #       - "80:80"
  nginx:
    build: ./nginx
    links:
        - webapp
    ports:
        - "80:80"