version: '2.2'
services:
  webapp:
    build: .
    image: kruny1001/webapp
    expose:
      - "3838"
    volumes:
      - ./shinyapps/:/srv/shiny-server/
      - ./data_12_19_2017/:/srv/data/
      - ./countsData/:/srv/data/            # read app
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/
    command: ["/usr/bin/shiny-server.sh"]
  nginx:
    build: ./nginx
    image: nginx:1.1
    cpus: 0.1
    links:
        - webapp
    ports:
        - "80:80"
