version: '2'
services:
  web:
    build: .
    ports:
      - "80:3838"
    volumes:
      #- ./shinyapps:/srv/shiny-server/ # this volume only for dev 
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/
      
    command: ["/usr/bin/shiny-server.sh"]