version: "2.2"
services:
  webapp:
    build: .
    image: webapp
    mem_limit: 12g
    mem_reservation: 6g
    mem_swappiness: 5
    # expose:
      # - "3838"
    ports:
      - 3939:3838
    volumes:
      - ./shinyapps/:/srv/shiny-server/
      - ./data/:/srv/data/
      - ./countsData/:/srv/countsData/ # read app
      - ./shinylog/:/var/log/shiny-server/
      - ./config/:/etc/shiny-server/
      - ./classes/:/usr/local/src/myscripts/

  # nginx:
  #   build: ./nginx
  #   image: nginx
  #   cpus: 0.1
  #   links:
  #       - webapp
  #   ports:
  #       - "8888:8888"
